<?xml version="1.0" encoding="UTF-8"?>
<!--

    This confidential and proprietary software may be used only as authorized
    by a licensing agreement from Linty Services.
    (c) Copyright 2016-2026 Linty Services
    ALL RIGHTS RESERVED
    The entire notice above must be reproduced on all authorized copies.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.lintyservices</groupId>
    <artifactId>sonar-plugin-parent-pom</artifactId>
    <version>1.1.0</version>
  </parent>

  <groupId>com.lintyservices.sonar.plugins.modelsim</groupId>
  <artifactId>parent</artifactId>
  <version>1.16.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Linty ModelSim / QuestaSim</name>
  <description>Code coverage from ModelSim / QuestaSim report</description>

  <modules>
    <module>sonar-modelsim-plugin</module>
    <!--See
    'its' profile to activate this module-->
    <!--<module>modelsim-its</module>-->
  </modules>

  <scm>
    <connection>scm:git:github.com:Linty-Services/sonar-modelsim-plugin.git</connection>
    <developerConnection>scm:git:github.com:Linty-Services/sonar-modelsim-plugin.git</developerConnection>
    <url>https://github.com/Linty-Services/sonar-modelsim-plugin.git</url>
  </scm>

  <issueManagement>
    <system>GitHub Issues</system>
    <url>https://github.com/Linty-Services/sonar-modelsim-plugin/issues</url>
  </issueManagement>

  <ciManagement>
    <system>GitHub Actions</system>
    <url>https://github.com/Linty-Services/sonar-modelsim-plugin/actions</url>
  </ciManagement>

  <distributionManagement>
    <repository>
      <id>github</id>
      <name>GitHub Packages</name>
      <url>https://maven.pkg.github.com/linty-services/sonar-modelsim-plugin</url>
    </repository>
  </distributionManagement>

  <repositories>
    <repository>
      <id>github</id>
      <url>https://maven.pkg.github.com/linty-services/*</url>
    </repository>
  </repositories>

  <profiles>
    <profile>
      <id>its</id>
      <modules>
        <module>modelsim-its</module>
      </modules>
    </profile>
  </profiles>
</project>
