<?xml version="1.0" encoding="UTF-8"?>
<!--

    This confidential and proprietary software may be used only as authorized
    by a licensing agreement from Linty Services.
    (c) Copyright 2016-2026 Linty Services
    ALL RIGHTS RESERVED
    The entire notice above must be reproduced on all authorized copies.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.lintyservices.sonar.plugins.modelsim</groupId>
    <artifactId>parent</artifactId>
    <version>1.15.0-SNAPSHOT</version>
  </parent>

  <artifactId>modelsim-its</artifactId>
  <name>Linty ModelSim / QuestaSim :: Integration Tests</name>

  <dependencies>
    <dependency>
      <groupId>com.lintyservices</groupId>
      <artifactId>test-harness</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.sonarsource.orchestrator</groupId>
      <artifactId>sonar-orchestrator-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
